### ISSUE TITLE
Drag is not working

### ISSUE THREAD

**Issue by shrinathdarur** [dmitrilc/DaniwebRecyclerViewSwipeToRemove#1]
Hi , I just tried running your code. swipe to delete is working but drag to change position is not working

**Comment by dmitrilc** [comment]
Hi friend, I just re-run the project on a fresh git clone of this remote and it is working for me, same as the Gif posted on Daniweb.com. To activate the drag-and-drop, you need to hold the item with your pointer or finger for about a second.

**Comment by shrinathdarur** [comment]
Hi , Its working as you suggested .  Thank you friend :)
